### ISSUE TITLE
adapter_config.json

### ISSUE THREAD

**Issue by GIANLUCARU** [lamm-mit/MeLM#1]
Hello,
I got this error:

HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/MechGPT-13b_v106C/resolve/main/adapter_config.json

when I run 

model = PeftModel.from_pretrained(model_base, peft_model_id,
                                                               )

in notebook: MechGPT inference

**Comment by lamm-mit** [comment]
The repository is public, you can find it here: https://huggingface.co/lamm-mit/MeLM/tree/main/MechGPT-13b_v106C

The reason is why your loading command didn't work is likely because the command expects the folder 'MechGPT-13b_v106C' to be local. 

I suggest downloading the entire folder and store it in a subdir with said name. Then the model should load without issue. You can do this as follows:
```
from huggingface_hub import HfApi, hf_hub_download

def download_subfolder(repo_id, subfolder, local_dir):
    api = HfApi()
    repo_files = api.list_repo_files(repo_id=repo_id)
    subfolder_files = [f for f in repo_files if f.startswith(subfolder)]
    for filename in subfolder_files:
        hf_hub_download(repo_id=repo_id, filename=filename, cache_dir=local_dir)
        print(f"Downloaded {filename} to {local_dir}")

# Example 
repo_id = 'lamm-mit/MeLM'
subfolder = 'MechGPT-13b_v106C'
local_dir = './MechGPT-13b_v106C'  # Local directory to save the files
download_subfolder(repo_id=repo_id, subfolder=subfolder, local_dir=local_dir)
```
